# Generated by Django 5.0.5 on 2024-05-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Nombre lista')),
                ('descrption', models.CharField(max_length=400, null=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa/pausa')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'db_table': 'listas',
            },
        ),
    ]
