# Generated by Django 5.0.5 on 2024-05-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_formulario_email_alter_formulario_name_list_and_more'),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='name_list',
        ),
        migrations.AddField(
            model_name='formulario',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listas.lista', verbose_name='lista_id'),
        ),
    ]
